### ISSUE TITLE
Conv-TasNet Cumulative Layer Norm Bug?

### ISSUE THREAD

**Issue by michelg10** [tky1117/DNN-based_source_separation#101]
shouldn't lines 78-92 be

`
step_sum = input.sum(dim=1) # -> (batch_size, T)
cum_sum = torch.cumsum(step_sum, dim=1) # -> (batch_size, T)
        
cum_num = torch.arange(C, C*(T+1), C, dtype=torch.float) # -> (T, ): [C, 2*C, ..., T*C]
cum_mean = cum_sum / cum_num # (batch_size, T)
cum_var = (cum_sum - cum_mean)**2/cum_num
        
cum_mean = cum_mean.unsqueeze(dim=1)
cum_var = cum_var.unsqueeze(dim=1)
        
output = (input - cum_mean) / (torch.sqrt(cum_var) + eps) * self.gamma + self.beta
`

according to the Conv-TasNet paper?

**Comment by tky823** [comment]
My `CumulativeLayerNorm1d` is based on [official implementation](https://github.com/naplab/Conv-TasNet/blob/master/utility/models.py#L8-L45). You can compare it with mine [here](https://colab.research.google.com/gist/tky823/eaa3f32d7f3021c6ed9ca272172019db/check_layer_norm.ipynb).
If there is any possibility that I have misunderstood something, let me know in more detail.

**Comment by michelg10** [comment]
compared to the official implementation, your code writes cum_var=cum_squared_mean - cum_mean**2 while the official code writes cum_var = (cum_pow_sum - 2*cum_mean*cum_sum) / entry_cnt + cum_mean.pow(2).

then cum_squared_mean should = (cum_pow_sum - 2*cum_mean*cum_sum) / entry_cnt
In your code cum_squared_mean=cum_squared_sum/cum_num. as entry_cnt=cum_sum,
cum_squared_sum should = cum_pow_sum-2*cum_mean*cum_sum

however cum_squared_sum is defined as torch.cumsum(step_pow_sum, dim=1) which equals cum_pow_sum in the official implementation, so you're missing 2*cum_mean*cum_sum.

am I missing anything here? or is this omitted for a speed / accuracy tradeoff?

**Comment by tky823** [comment]
![formula](https://render.githubusercontent.com/render/math?math=\begin{align*}%20f%26=(f_{n,k})\in\mathbb{R}^{N\times%20T}...(\mathrm{input})%20\end{align*})
![formula](https://render.githubusercontent.com/render/math?math=\begin{align*}%20s_{k}%20%26=\sum_{n=1}^{N}f_{n,k}...(\mathrm{step\_sum})%20\end{align*})
![formula](https://render.githubusercontent.com/render/math?math=\begin{align*}%20\tilde{s}_{k}%20%26=\sum_{n=1}^{N}f_{n,k}^{2}...(\mathrm{step\_pow\_sum})%20\end{align*})
![formula](https://render.githubusercontent.com/render/math?math=\begin{align*}%20c_{k}%20%26=%20\sum_{t=1}^{k}s_{t}...(\mathrm{cum\_sum})%20\end{align*})
![formula](https://render.githubusercontent.com/render/math?math=\begin{align*}%20\tilde{c}_{k}%20%26=%20\sum_{t=1}^{k}\tilde{s}_{t}...(\mathrm{cum\_pow\_sum})%20\end{align*})
![formula](https://render.githubusercontent.com/render/math?math=\begin{align*}%20\mu_{k}%20%26=%20\frac{1}{Nk}c_{k}...(\mathrm{cum\_mean})%20\end{align*})

In official implementation:
![formula](https://render.githubusercontent.com/render/math?math=\begin{align*}%20\sigma_{k}^{2}%20%26=%20\frac{1}{Nk}(\tilde{c}_{k}%20-%202\mu_{k}c_{k})%20%2B%20\mu_{k}^{2}%20=%20\frac{1}{Nk}\tilde{c}_{k}%20-%202\mu_{k}\left(\frac{1}{Nk}c_{k}\right)%20%2B%20\mu_{k}^{2}%20=%20\frac{1}{Nk}\tilde{c}_{k}%20-%202\mu_{k}^{2}%20%2B%20\mu_{k}^{2}%20=%20\frac{1}{Nk}\tilde{c}_{k}%20-%20\mu_{k}^{2}...(\mathrm{cum\_var})%20\end{align*})

In my repo:
![formula](https://render.githubusercontent.com/render/math?math=\begin{align*}%20\tilde{\mu}_{k}%20%26=%20\frac{1}{Nk}\tilde{c}_{k}...(\mathrm{cum\_pow\_mean})%20\end{align*})
![formula](https://render.githubusercontent.com/render/math?math=\begin{align*}%20\sigma_{k}^{2}%20%26=%20\tilde{\mu}_{k}-\mu_{k}^{2}%20=%20\frac{1}{Nk}\tilde{c}_{k}%20-%20\mu_{k}^{2}...(\mathrm{cum\_var})%20\end{align*})

I renamed some variables in `check_layer_norm.ipynb` at [https://github.com/tky823/DNN-based_source_separation/issues/101#issuecomment-975686051](https://github.com/tky823/DNN-based_source_separation/issues/101#issuecomment-975686051) for readability.

**Comment by michelg10** [comment]
My bad! thank you for clearing it up!
