### ISSUE TITLE
missing SPEAKERS.TXT for example

### ISSUE THREAD

**Issue by jehall** [tky1117/DNN-based_source_separation#108]
When running the **0. Preparation** section of the [Example in the Readme.md file](https://github.com/tky823/DNN-based_source_separation#example), I get an error:
`FileNotFoundError: [Errno 2] No such file or directory: '../../../dataset/SPEAKERS.TXT'`
If I just create an empty file, `./prepare_librispeech.sh` runs without error, but then `./train.sh` gives an error `ValueError: num_samples should be a positive integer value, but got num_samples=0`
Please give some advice on the required content and format of `SPEAKERS.TXT`
Thank you.

**Comment by tky823** [comment]
Now, I've updated the example.
See [https://colab.research.google.com/github/tky823/DNN-based_source_separation/blob/main/egs/tutorials/conv-tasnet/train_librispeech.ipynb](https://colab.research.google.com/github/tky823/DNN-based_source_separation/blob/main/egs/tutorials/conv-tasnet/train_librispeech.ipynb).

**Comment by jehall** [comment]
Thank you!  I am now running https://github.com/tky823/DNN-based_source_separation/blob/main/egs/tutorials/conv-tasnet/train.sh with a training dataset of 83256 samples using the example.
